### ISSUE TITLE
Response wrapper

### ISSUE THREAD

**Issue by adammbalogh** [jsor/stack-jwt#3]
I'm thinking about a response wrapper around [this line](https://github.com/jsor/stack-jwt/blob/master/src/JWT.php#L38).

I use your package in a [rest micro framework](https://github.com/phprest/phprest) and it would be nice if I could return with a custom formatted response (with xml/json not just plain html and my own headers).

There could be an optional wrapper option...

What do you think?

**Comment by jsor** [comment]
Isn't that the purpose of Stack itself, allowing to wrap any app/middleware and manipulate the response?

``` php
$app = new MyApp();
$jwt = new Jsor\Stack\JWT($app);
$inline = new Stack\Inline($jwt, function($app, $request, $type, $catch) {
    $response = $app->handle($app, $request, $type, $catch);

    if (401 === $reponse->getStatusCode()) {
        $myChallengeReponse = new Reponse();

        // Configure your own challenge response here

        return $myChallengeReponse;
    }

    return $response;
});
```

**Comment by adammbalogh** [comment]
True, I should wrap it myself. It's not your package's responsibility.

Thanks.
